--
stages:
  - lint
  - build

lint:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - mkdir -p reports
    - hadolint --ignore SC2038 --ignore DL4006 --ignore DL3013 -f gitlab_codeclimate Dockerfile > reports/hdolint-$(md5sum Dockerfile | cut -d " " -f1).json
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    when: always
    reports:
      codequality:
        - "reports/*"
    paths:
      - "reports/*"

build:
  stage: build
  image: docker:stable
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/docker/salt-minion .
    - docker push $CI_REGISTRY/docker/salt-minion
  tags:
    - k8s-node1
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
